### ISSUE TITLE
tooltip shows incorrect y value for stacked bar charts

### ISSUE THREAD

**Issue by estollnitz** [krzysu/flot.tooltip#3]
I used flot.stack to create a stacked bar chart.  It stacks the bars by changing the data points.  The flot.tooltip plugin displayed the modified data point's y value (which is the sum of the heights of the stacked bars) when formatting "%y".  Instead, it should show the original data point's y value (the height of a single bar within the stack).

Looks like flot.tooltip is getting the x and y values from item.datapoint, which is the modified data point.  The original data point is available in item.series.data[item.dataIndex].

**Comment by sumit1191** [comment]
I am using tooltip but data on tooltip is showing incorrectly . I have two bar on bar is showing correctly but other is showing wrong. i am attaching image1 and image2 . In the image1 tooltip data is showing correctly on the green bar while in image2 on blue bar showing tooltip data in incorrectly. on the blue bar should also showing X axis value as green bar but its showing 20 instead of COD maintenance.

Please suggest someone.
![image1](https://user-images.githubusercontent.com/32646675/31347839-a7eaa1ae-aceb-11e7-97cb-d5ce7d673583.jpg)
![image2](https://user-images.githubusercontent.com/32646675/31347838-a7861a72-aceb-11e7-83ab-218bb6905c65.jpg)
